import sophiaPhoto from "./sophia-dos-santos.jpg";
import bookCover from "./trono-de-vidro.jpg";
import coffeePhoto from "./cafe-sophia.jpg";
import angeloniImagem1 from "./angeloni-imagem-1.png";
import angeloniImagem2 from "./angeloni-imagem-2.png";
import angeloniImagem3 from "./angeloni-imagem-3.png";
import angeloniImagem4 from "./angeloni-imagem-4.png";
import angeloniImagem5 from "./angeloni-imagem-5.png";
import bookingImagem1 from "./booking-imagem-1.png";
import bookingImagem2 from "./booking-imagem-2.png";
import cardInterativoCapturaDeTelaBuscaDeAcomodacoes from "./card-interativo-captura-de-tela-busca-de-acomodacoes.png";
import cardInterativoCapturaDeTelaInicio from "./card-interativo-captura-de-tela-inicio.png";
import cardInterativoGroup1 from "./card-interativo-group-1.png";
import cardInterativoGroup2 from "./card-interativo-group-2.png";
import cardInterativoGroup4 from "./card-interativo-group-4.png";
import cardInterativoScreencaptureBookingHotelBrSeteIlhasPtBrHtml202608262116121 from "./card-interativo-screencapture-booking-hotel-br-sete-ilhas-pt-br-html-2026-08-26-21-16-12-1.png";
import cursivaImagem1 from "./cursiva-imagem-1.png";
import cursivaImagem2 from "./cursiva-imagem-2.png";
import cursivaImagem3 from "./cursiva-imagem-3.png";
import cursivaImagem4 from "./cursiva-imagem-4.png";
import cursivaImagem5 from "./cursiva-imagem-5.png";
import cursivaImagem6 from "./cursiva-imagem-6.png";
import miniaturaTelaInicialAngeloni from "./miniatura-tela-inicial-angeloni.png";
import miniaturaTelaInicialBooking from "./miniatura-tela-inicial-booking.png";
import miniaturaTelaInicialCursiva from "./miniatura-tela-inicial-cursiva.png";
import telasAngeloniCadastrar1 from "./telas-angeloni-cadastrar-1.png";
import telasAngeloniDescricaoDoItem1 from "./telas-angeloni-descricao-do-item-1.png";
import telasAngeloniEntrar1 from "./telas-angeloni-entrar-1.png";
import telasAngeloniPesquisa1 from "./telas-angeloni-pesquisa-1.png";
import telasAngeloniSplashScreenAngeloni3 from "./telas-angeloni-splash-screen-angeloni-3.png";
import telasAngeloniSugestoesInteligentes1 from "./telas-angeloni-sugestoes-inteligentes-1.png";
import telasAngeloniTelaInicialAngeloni3 from "./telas-angeloni-tela-inicial-angeloni-3.png";
import telasAngeloniTelaPesquisar1 from "./telas-angeloni-tela-pesquisar-1.png";
import telasBookingBuscaDeAcomodacoesMobile from "./telas-booking-busca-de-acomodacoes-mobile.png";
import telasBookingBuscaDeAcomodacoesWeb from "./telas-booking-busca-de-acomodacoes-web.png";
import telasBookingDetalhesDaAcomodacaoMobile from "./telas-booking-detalhes-da-acomodacao-mobile.png";
import telasBookingDetalhesDaAcomodacaoWeb from "./telas-booking-detalhes-da-acomodacao-web.png";
import telasBookingInicioBooking from "./telas-booking-inicio-booking.png";
import telasBookingInicioWebBooking from "./telas-booking-inicio-web-booking.png";
import telasCursivaImportarProva1 from "./telas-cursiva-importar-prova-1.png";
import telasCursivaLogin1 from "./telas-cursiva-login-1.png";
import telasCursivaOnboardingDadosPessoais1 from "./telas-cursiva-onboarding-dados-pessoais-1.png";
import telasCursivaOnboardingEscola11 from "./telas-cursiva-onboarding-escola-1-1.png";
import telasCursivaOnboardingIniciar1 from "./telas-cursiva-onboarding-iniciar-1.png";
import telasCursivaOnboardingMaterias1 from "./telas-cursiva-onboarding-materias-1.png";
import telasCursivaOnboardingModalidade1 from "./telas-cursiva-onboarding-modalidade-1.png";
import telasCursivaOnboardingNivelDeEnsino1 from "./telas-cursiva-onboarding-nivel-de-ensino-1.png";
import telasCursivaOnboardingPreparandoAmbiente11 from "./telas-cursiva-onboarding-preparando-ambiente-1-1.png";
import telasCursivaTelaDeProvas12 from "./telas-cursiva-tela-de-provas-1-2.png";
import telasCursivaTelaDeProvas31 from "./telas-cursiva-tela-de-provas-3-1.png";
import telasCursivaTelaDeProvas51 from "./telas-cursiva-tela-de-provas-5-1.png";
import telasCursivaTelaInicialAssistente2 from "./telas-cursiva-tela-inicial-assistente-2.png";
import telasCursivaTelaInicialTour1 from "./telas-cursiva-tela-inicial-tour-1.png";

export const sophiaPhotoUrl = sophiaPhoto;
export const bookCoverUrl = bookCover;
export const coffeePhotoUrl = coffeePhoto;
export const angeloniImagem1Url = angeloniImagem1;
export const angeloniImagem2Url = angeloniImagem2;
export const angeloniImagem3Url = angeloniImagem3;
export const angeloniImagem4Url = angeloniImagem4;
export const angeloniImagem5Url = angeloniImagem5;
export const bookingImagem1Url = bookingImagem1;
export const bookingImagem2Url = bookingImagem2;
export const cardInterativoCapturaDeTelaBuscaDeAcomodacoesUrl = cardInterativoCapturaDeTelaBuscaDeAcomodacoes;
export const cardInterativoCapturaDeTelaInicioUrl = cardInterativoCapturaDeTelaInicio;
export const cardInterativoGroup1Url = cardInterativoGroup1;
export const cardInterativoGroup2Url = cardInterativoGroup2;
export const cardInterativoGroup4Url = cardInterativoGroup4;
export const cardInterativoScreencaptureBookingHotelBrSeteIlhasPtBrHtml202608262116121Url = cardInterativoScreencaptureBookingHotelBrSeteIlhasPtBrHtml202608262116121;
export const cursivaImagem1Url = cursivaImagem1;
export const cursivaImagem2Url = cursivaImagem2;
export const cursivaImagem3Url = cursivaImagem3;
export const cursivaImagem4Url = cursivaImagem4;
export const cursivaImagem5Url = cursivaImagem5;
export const cursivaImagem6Url = cursivaImagem6;
export const miniaturaTelaInicialAngeloniUrl = miniaturaTelaInicialAngeloni;
export const miniaturaTelaInicialBookingUrl = miniaturaTelaInicialBooking;
export const miniaturaTelaInicialCursivaUrl = miniaturaTelaInicialCursiva;
export const telasAngeloniCadastrar1Url = telasAngeloniCadastrar1;
export const telasAngeloniDescricaoDoItem1Url = telasAngeloniDescricaoDoItem1;
export const telasAngeloniEntrar1Url = telasAngeloniEntrar1;
export const telasAngeloniPesquisa1Url = telasAngeloniPesquisa1;
export const telasAngeloniSplashScreenAngeloni3Url = telasAngeloniSplashScreenAngeloni3;
export const telasAngeloniSugestoesInteligentes1Url = telasAngeloniSugestoesInteligentes1;
export const telasAngeloniTelaInicialAngeloni3Url = telasAngeloniTelaInicialAngeloni3;
export const telasAngeloniTelaPesquisar1Url = telasAngeloniTelaPesquisar1;
export const telasBookingBuscaDeAcomodacoesMobileUrl = telasBookingBuscaDeAcomodacoesMobile;
export const telasBookingBuscaDeAcomodacoesWebUrl = telasBookingBuscaDeAcomodacoesWeb;
export const telasBookingDetalhesDaAcomodacaoMobileUrl = telasBookingDetalhesDaAcomodacaoMobile;
export const telasBookingDetalhesDaAcomodacaoWebUrl = telasBookingDetalhesDaAcomodacaoWeb;
export const telasBookingInicioBookingUrl = telasBookingInicioBooking;
export const telasBookingInicioWebBookingUrl = telasBookingInicioWebBooking;
export const telasCursivaImportarProva1Url = telasCursivaImportarProva1;
export const telasCursivaLogin1Url = telasCursivaLogin1;
export const telasCursivaOnboardingDadosPessoais1Url = telasCursivaOnboardingDadosPessoais1;
export const telasCursivaOnboardingEscola11Url = telasCursivaOnboardingEscola11;
export const telasCursivaOnboardingIniciar1Url = telasCursivaOnboardingIniciar1;
export const telasCursivaOnboardingMaterias1Url = telasCursivaOnboardingMaterias1;
export const telasCursivaOnboardingModalidade1Url = telasCursivaOnboardingModalidade1;
export const telasCursivaOnboardingNivelDeEnsino1Url = telasCursivaOnboardingNivelDeEnsino1;
export const telasCursivaOnboardingPreparandoAmbiente11Url = telasCursivaOnboardingPreparandoAmbiente11;
export const telasCursivaTelaDeProvas12Url = telasCursivaTelaDeProvas12;
export const telasCursivaTelaDeProvas31Url = telasCursivaTelaDeProvas31;
export const telasCursivaTelaDeProvas51Url = telasCursivaTelaDeProvas51;
export const telasCursivaTelaInicialAssistente2Url = telasCursivaTelaInicialAssistente2;
export const telasCursivaTelaInicialTour1Url = telasCursivaTelaInicialTour1;
