/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AngeloniRouteImport } from './routes/angeloni'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CursivaRouteImport } from './routes/cursiva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngeloniRoute = AngeloniRouteImport.update({
  id: '/angeloni',
  path: '/angeloni',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CursivaRoute = CursivaRouteImport.update({
  id: '/cursiva',
  path: '/cursiva',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angeloni': typeof AngeloniRoute
  '/booking': typeof BookingRoute
  '/cursiva': typeof CursivaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angeloni': typeof AngeloniRoute
  '/booking': typeof BookingRoute
  '/cursiva': typeof CursivaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angeloni': typeof AngeloniRoute
  '/booking': typeof BookingRoute
  '/cursiva': typeof CursivaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/angeloni' | '/booking' | '/cursiva'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/angeloni' | '/booking' | '/cursiva'
  id: '__root__' | '/' | '/angeloni' | '/booking' | '/cursiva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngeloniRoute: typeof AngeloniRoute
  BookingRoute: typeof BookingRoute
  CursivaRoute: typeof CursivaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angeloni': {
      id: '/angeloni'
      path: '/angeloni'
      fullPath: '/angeloni'
      preLoaderRoute: typeof AngeloniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursiva': {
      id: '/cursiva'
      path: '/cursiva'
      fullPath: '/cursiva'
      preLoaderRoute: typeof CursivaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngeloniRoute: AngeloniRoute,
  BookingRoute: BookingRoute,
  CursivaRoute: CursivaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
